{{ if .Values.alerts.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nais-contests-alerts
spec:
  groups:
    - name: nais-contests-alerts
      rules:
        - alert: ExternalURLsFailed
          expr: sum(probe_success{instance=~"https://.*"}) == 0
          for: 5m
          labels:
            namespace: nais-system
            severity: critical
          annotations:
            consequence: External URLs is unavailable
            action: -|
              Check external connectivity from cluster
              <https://monitoring.nais.io/d/istuhtS4z/contests?orgId=1&var-tenant={{ .Values.tenant }}&var-cluster_id={{ .Values.tenant }}-{{ .Values.env }}|Grafana Dashboard>

        {{- if .Values.contests.storage.enabled }}
        - alert: PersistenceFailed
          expr: probe_success{instance=~"http://contests/.*/test"} == 0
          for: 5m
          labels:
            namespace: nais-system
            severity: critical
          annotations:
            consequence: Persistence type {{ "{{ $labels.instance }}" }} may be unavailable in cluster.
            action: <https://monitoring.nais.io/d/istuhtS4z/contests?orgId=1&var-tenant={{ .Values.tenant }}&var-cluster_id={{ .Values.tenant }}-{{ .Values.env }}|Grafana Dashboard>
        {{- end }}
        {{- if .Values.contests.accessPolicy.enabled }}
        - alert: AccessPolicyAllowed
          expr: probe_success{instance=~"http://contests/ping"} == 0
          for: 5m
          labels:
            namespace: nais-system
            severity: critical
          annotations:
            consequence: Access policies may not work correctly in cluster.
            action: <https://monitoring.nais.io/d/istuhtS4z/contests?orgId=1&var-tenant={{ .Values.tenant }}&var-cluster_id={{ .Values.tenant }}-{{ .Values.env }}|Grafana Dashboard>
            summary: Blackbox exporter is unable to access {{ "{{ $labels.instance }}" }} in cluster.
        - alert: AccessPolicyDeny
          expr: probe_success{instance=~"http://contests-noaccess/ping"} == 1
          for: 5m
          labels:
            namespace: nais-system
            severity: critical
          annotations:
            consequence: Access policies may not work correctly in cluster.
            action: <https://monitoring.nais.io/d/istuhtS4z/contests?orgId=1&var-tenant={{ .Values.tenant }}&var-cluster_id={{ .Values.tenant }}-{{ .Values.env }}|Grafana Dashboard>
            summary: Blackbox exporter is able to access {{ "{{ $labels.instance }}" }} in cluster when it shouldn't.
        {{- end }}
{{- end }}