apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: contests
  labels:
    {{- include "contests.labels" . | nindent 4 }}
    team: nais
spec:
  accessPolicy:
    inbound:
      rules:
        - application: {{ .Chart.Name }}-blackbox-exporter
  image: "{{ .Values.contests.image.repository }}/{{ .Values.contests.image.name }}:{{ .Values.contests.image.tag | default .Chart.AppVersion }}"
  port: 8080
  liveness:
    path: /ping
  readiness:
    path: /ping
  replicas:
    min: 2
    max: 2
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi
  skipCaBundle: true
  env:
    - name: "foo"
      value: "bar"
    - name: "BUCKET_NAME"
      value: "{{ .Chart.Name }}-{{ .Values.tenant }}-{{ .Values.env }}"
  {{ if or .Values.contests.buckets.enabled .Values.contests.database.enabled }}
  gcp:
  {{ end }}
    {{ if .Values.contests.buckets.enabled }}
    buckets:
      - name: "{{ .Chart.Name }}-{{ .Values.tenant }}-{{ .Values.env }}"
    {{ end }}
    {{ if .Values.contests.database.enabled }}
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: contests
    {{ end }}
  {{ if .Values.contests.kafka.enabled }}
  kafka:
    pool: {{ .Values.contests.kafka.pool }}
  {{ end }}
  ingresses:
    {{- toYaml .Values.contests.ingresses | nindent 4 }}

---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    {{- include "contests.labels" . | nindent 4 }}
    team: nais
  name: contests-noaccess
spec:
  image: "{{ .Values.contests.image.repository }}/{{ .Values.contests.image.name }}:{{ .Values.contests.image.tag | default .Chart.AppVersion }}"
  liveness:
    path: /ping
  port: 8080
  prometheus:
    enabled: true
    path: /internal/metrics
  readiness:
    path: /ping
  replicas:
    max: 2
    min: 2
  skipCaBundle: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
