---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-blackbox-exporter
  labels:
    {{- include "contests.labels" . | nindent 4 }}
data:
  config.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          follow_redirects: true
          preferred_ip_protocol: "ip4"
          ip_protocol_fallback: false
---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-blackbox-exporter
  labels:
    {{- include "contests.labels" . | nindent 4 }}
    team: nais
spec:
  image: prom/blackbox-exporter:v0.23.0
  accessPolicy:
    outbound:
      rules:
        - application: contests
      external:
        - host: dns.google
        - host: 1dot1dot1dot1.cloudflare-dns.com
  filesFrom:
    - configmap: {{ .Release.Name }}-blackbox-exporter
      mountPath: /etc/blackbox_exporter
  port: 9115
  replicas:
    max: 2
    min: 2
  skipCaBundle: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-prometheus-to-blackbox-exporter
  labels:
    {{- include "contests.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: nais-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-blackbox-exporter
  policyTypes:
  - Ingress
---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: {{ .Release.Name }}-probes
  labels:
    {{- include "contests.labels" . | nindent 4 }}
    nais.io/prometheus: "nais"
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: {{ .Release.Name }}-blackbox-exporter.{{ .Release.Namespace }}:80
  targets:
    staticConfig:
      static:
        - http://contests/ping
        {{- if .Values.contests.storage.enabled }}
        - http://contests/database
        - http://contests/bucket
        {{- end }}
        {{- if .Values.contests.bigquery.enabled }}
        - http://contests/bigquery
        {{- end }}
        {{- if .Values.contests.opensearch.enabled }}
        - http://contests/opensearch
        {{- end }}
        {{- if .Values.contests.valkey.enabled }}
        - http://contests/valkey
        {{- end }}
        {{- if .Values.contests.kafka.enabled }}
        - http://contests/kafka
        {{- end }}
        {{- if .Values.contests.azureApp.enabled }}
        - http://contests/azure
        {{- end }}
        {{- if .Values.contests.accessPolicy.enabled }}
        - http://contests-noaccess/ping
        - https://google.com
        {{- end }}
        - https://dns.google
        - https://1dot1dot1dot1.cloudflare-dns.com
      {{range .Values.blackboxExporter.additionalTargetURLs }}
        - {{ . }}
      {{end}}
