{{- if .Values.contests.opensearch.enabled }}
apiVersion: aiven.io/v1alpha1
kind: OpenSearch
metadata:
  labels:
    team: nais
  name: opensearch-{{ .Release.Namespace }}-{{ .Release.Name }}
spec:
  plan: hobbyist
  project: {{ .Values.contests.opensearch.project }}
{{- end }}