dependencies:
  - allOf:
    - monitoring
environmentKinds:
  - tenant
  - legacy
values:
  blackboxExporter.additionalTargetURLs:
    displayName: Additional Target URLs
    config:
      type: string_array
  contests.kafka.enabled:
    displayName: Enable Kafka checks
    config:
      type: bool
  contests.kafka.pool:
    displayName: Kafka pool
    computed:
      template: '"{{ .Env.aiven_project }}"'
  contests.opensearch.project:
    displayName: OpenSearch project
    computed:
      template: '"{{ .Env.aiven_project }}"'
  contests.storage.enabled:
    displayName: Enable storage checks (GCP postgres + bucket)
    config:
      type: bool
  contests.bigquery.enabled:
    displayName: Enable BigQuery checks
    config:
      type: bool
  contests.opensearch.enabled:
    displayName: Enable OpenSearch checks
    config:
      type: bool
  contests.valkey.enabled:
    displayName: Enable Valkey checks
    config:
      type: bool
  contests.azureApp.enabled:
    displayName: Enable Azure app checks
    config:
      type: bool
  contests.postgres.enabled:
    displayName: Enable Postgres app checks
    config:
      type: bool
