name: Build and push image and chart

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  build:
    uses: nais/actions/.github/workflows/mise-build-deploy-fasit.yaml@f86b20948998a0e6b81af1cab89077c81c6161a7
    with:
      builds-docker: true
      builds-chart: true
      deploys-to-fasit: true
      mise-tasks: '["fmt", "check"]'
      targets: |
        [
          { "target": { "kind": "tenant", "tenant": "ci-nais" }, "wait": true },
          { "target": { "kind": "tenant" } }
        ]
    secrets:
      NAIS_IO_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
