name: Build and push image and chart

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  build:
    uses: nais/actions/.github/workflows/mise-build-deploy-fasit.yaml@aa4b3f170c7d73bc435f0176e99e7072814e87db
    with:
      builds-docker: true
      builds-chart: true
      deploys-to-fasit: true
      mise-tasks: '["fmt", "check"]'
      targets: |
        [
          { "target": { "kind": "tenant", "tenant": "ci-nais" }, "wait": true },
          { "target": { "kind": "tenant" } }
        ]
    secrets:
      NAIS_IO_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
