name: Build and push image and chart

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  builds:
    uses: nais/actions/.github/workflows/mise-build-deploy-fasit.yaml@f5878ae809bc0adec962432f8440e618f35a986a
    with:
      builds-docker: true
      builds-chart: true
      deploys-to-fasit: true
      mise-tasks: '["fmt", "check"]'
      targets: |
        [
          { "target": { "kind": "management", "tenant": "ci-nais" }, "wait": true },
          { "target": { "kind": "management" } }
        ]
    secrets:
      NAIS_IO_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
