{{- if .Values.contests.opensearch.enabled }}
apiVersion: nais.io/v1
kind: OpenSearch
metadata:
  name: {{ .Release.Name }}
spec:
  tier: SingleNode
  memory: 4GB
  storageGB: 80
  version: "3.6"
{{- end }}
